locale: pl
mysql:
  host: localhost
  port: 3306
  user: root
  pass: ''
  base: leviathanproject
# You need to take a bukkit reference and search class for it.
# For example EntityEnderCrystal, or EnderCrystal, EntityBlaze or EntityZombie, or just Zombie
# Don't need to put Entity
# Its a entity placed on center of your guild
classPathEntity: EnderCrystal
prefixes:
  other: '&f'
  ally: '&8[&6%tag%&8] &6'
  enemy: '&8[&c%tag%&8] &c'
  friendly: '&8[&a%tag%&8] &a'
tab:
  header: '&9Leviathan&3Guilds'
  footer: '&9&lUltimate and fresh &3&lguild solution'
  update: # which slots to update every second, column:row
    - '1:1'
    - '2:1'
  1:
    1: '1'
    2: '2'
    3: '3'
    4: '4'
    5: '5'
    6: '6'
    7: '7'
    8: '8'
    9: '9'
    10: '10'
    11: '11'
    12: '12'
    13: '13'
    14: '14'
    15: '15'
    16: '16'
    17: '17'
    18: '18'
    19: '19'
    20: '20'
  2:
    1: '1'
    2: '2'
    3: '3'
    4: '4'
    5: '5'
    6: '6'
    7: '7'
    8: '8'
    9: '9'
    10: '10'
    11: '11'
    12: '12'
    13: '13'
    14: '14'
    15: '15'
    16: '16'
    17: '17'
    18: '18'
    19: '19'
    20: '20'
  3:
    1: '1'
    2: '2'
    3: '3'
    4: '4'
    5: '5'
    6: '6'
    7: '7'
    8: '8'
    9: '9'
    10: '10'
    11: '11'
    12: '12'
    13: '13'
    14: '14'
    15: '15'
    16: '16'
    17: '17'
    18: '18'
    19: '19'
    20: '20'
  4:
    1: '1'
    2: '2'
    3: '3'
    4: '4'
    5: '5'
    6: '6'
    7: '7'
    8: '8'
    9: '9'
    10: '10'
    11: '11'
    12: '12'
    13: '13'
    14: '14'
    15: '15'
    16: '16'
    17: '17'
    18: '18'
    19: '19'
    20: '20'